### ISSUE TITLE
More self host ? 

### ISSUE THREAD

**Issue by Ange-Cesari** [igorski/bitmappery#25]
Hey,

I understood that the person who maintains particularly likes integrations and online services, for instance: dropbox.

I think that these integrations are necessary for some people who use these services, but for others (especially in EU) who want "self host" the maximum of their uses, it can become limited. Saving the web page allows to get the service locally (offline) but not to use integrations. 

 I think it would be interesting to add more flexibility to leave the possibility to users (without necessarily adding a front-end) but at least to let via environment variables the possibility to choose its integrations. You use dropbox for example. It is totally possible to use minio to create s3 bucket and save photos.

Moreover I did a medium article on the integration of the outline-wiki service with minio : https://medium.com/@ange.cesari/how-to-deploy-outline-wiki-fully-self-hosted-no-tls-with-docker-compose-e50b57baaf73

To follow up on the outcome on docker  #18  I think there are things to do on the self host part and I would like to know your views on this.

**Comment by igorski** [comment]
Hi there, you raise an interesting topic.

Dropbox and Google Drive were chosen because for the web, they are pretty common third party services that are used among a large audience. Given that they come with well maintained SDK's they were easy to integrate. A rudimentary adapter-based API has been created where the BitMappery frontend calls interface methods to authenticate, browse folders and retrieve and save files.

At the same time, there are obviously a lot more storage services and since the topic of self hosting has been raised, I definitely can see a benefit to using S3, for instance. At that moment though, this raised the topic of how to organise the code base. S3 storage will for instance not be made available to the web version (as I will not create and expose any server side middleware to handle these requests as the buckets should be owned by the user).

But I like the idea of the Docker based self hosting setup. We can think of how to indeed use env variables to set up the third party integrations available to BitMappery, and how we can inject an external API to integrate with BitMappery's "third party adapter".

**Comment by Ange-Cesari** [comment]
Hey @igorski 


Since the docker issue has been settled, I would like to propose another idea. By hosting the image on dockerhub, it is possible to fill in the various services in a single file. This would allow to create a docker compose file that brings bitmappery but also minio in the same document.

If you manage to write the necessary code to allow connecting to a s3 bucket by giving its URL, its access key and its name, then it would be possible via environment variables to give out of the box a configuration that could work in just a few steps.

If you manage this environment variable part (obviously by adding the associated documentation) and you host the image on dockerhub.io, I am ready to write you the docker compose file and do the step by step documentation for minio setup with bitmappery.

**Comment by igorski** [comment]
Hey @Ange-Cesari how important is MinIO in this setup ? As in : do you want to use AWS S3 (and use Minio as a storage proxy) or do you want to use buckets directly inside a MinIO server ?

The reason I'm asking is because [minio-js cannot be used in the browser](https://github.com/minio/minio-js/issues/729#issuecomment-463538649) and its integration is severely complicated by the fact that BitMappery is a TypeScript project relying on an ES module system.

I understand that we can launch Minio inside a container when going for a self hosted BitMappery, but at the same time this requires writing a more complex API for a very specific use case, rather than using the official AWS SDK to directly connect to S3.

As for your setup, it would work the same : environment variables can control the configuration to access the bucket (and additionally whether you want to use Dropbox or Google Drive or not).

**Comment by Ange-Cesari** [comment]
Hi there,

To answer your question, I think minio is not just a classic storage system, I think it’s the best alternative to AWS S3. It’s free, open source, set up in 10 minutes, that’s how long it takes to create an aws account for developer. Minio is game changer in my opinion.

However, since minio is a s3 bucket, it uses the same s3 protocol as aws s3.

I think the minio-js integration you found is specific for minio, while the aws sdk is based only on the s3 protocol, and therefore should be usable with aws (not surprisingly) but also with minio.

I’m sure that’s what outline-wiki uses because basically their solution is supposed to be used for AWS S3, but using the same environment variables but adapting for minio worked. I think it’s the same here.

Feel free to see my article to understand more how to works with outline-wiki and minio.

**Comment by igorski** [comment]
Hi @Ange-Cesari 

You are right, the AWS SDK is not vendor locked to AWS S3, but should indeed work with any S3 implementation. By replacing the `minio-js` package with `@aws-sdk/client-s3` everything is now worker inside the web client.

I have created [this branch](https://github.com/igorski/bitmappery/tree/aws) which has a working integration that I tested against an AWS hosted bucket.

Could you have a look whether it works for your purposes ? There is also [this pull request](https://github.com/igorski/bitmappery/pull/30) with more details on configuration.

**Comment by Ange-Cesari** [comment]
Hey @igorski ,

as the issue has been treated in this PR : https://github.com/igorski/bitmappery/pull/30 that has been merged, I'm closing the issue.
